---
apiVersion: v1
kind: Service
metadata:
  name: micro-car
  namespace: default
  labels:
    name: micro-car
spec:
  ports:
    # the port that this service should serve on
    - name: http
      port: 80
      targetPort: 8081
      nodePort: 30002
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: micro-car
  type: LoadBalancer
