apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: micro-car
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: micro-car
    spec:
      containers:
        - name: car
          resources:
            limits:
              cpu: "10m"
          command: [
            "/micro",
            "--registry=kubernetes",
            "--register_ttl=60",
            "--register_interval=30",
            "--selector=cache",
            "--enable_stats",
            "sidecar"
          ]
          image: microhq/micro:kubernetes
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
            name: car-port
